# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'lambdalisue/vim-manpager'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'junegunn/fzf'
build =  './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'

[[plugins]]
repo = 'tversteeg/registers.nvim'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = '''
  call firenvim#install(0)
'''

[[plugins]]
repo = 'rickhowe/diffchar.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'tpope/vim-unimpaired'
