[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'roxma/vim-tmux-clipboard'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'

[[plugins]]
repo = 'alx741/vim-hindent'
