#!/usr/bin/env bash

set -e
sudo -v

if [ "$(uname -s)" == "Linux" ]
then

brew update
brew upgrade

brew install act
brew install actionlint
brew install alsa-lib
brew install anyenv
brew install autogen
brew install autossh
brew install bat
brew install bdw-gc
brew install berkeley-db
brew install berkeley-db@5
brew install binutils
brew install bison
brew install brotli
brew install bzip2
brew install c-ares
brew install ca-certificates
brew install cairo
brew install cmake
brew install cups
brew install curl
brew install dbus
brew install exa
brew install expat
brew install fd
brew install fontconfig
brew install fpp
brew install freetype
brew install fzf
brew install gcc
brew install gdbm
brew install gettext
brew install ghostscript
brew install ghq
brew install giflib
brew install git-delta
brew install git-now
brew install git-secrets
brew install glib
brew install glibc
brew install gmp
brew install gnu-getopt
brew install gnutls
brew install go
brew install gperf
brew install graphite2
brew install grex
brew install gron
brew install guile
brew install harfbuzz
brew install httpie
brew install icu4c
brew install isl
brew install isl@0.18
brew install jbig2dec
brew install jemalloc
brew install jpeg
brew install jpeg-turbo
brew install jq
brew install krb5
brew install kubernetes-cli
brew install lazygit
brew install libdrm
brew install libedit
brew install libelf
brew install libev
brew install libevent
brew install libffi
brew install libgit2
brew install libice
brew install libidn
brew install libidn2
brew install libmpc
brew install libnghttp2
brew install libnsl
brew install libpciaccess
brew install libpng
brew install libpthread-stubs
brew install libsm
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtirpc
brew install libtool
brew install libunistring
brew install libuv
brew install libva
brew install libvdpau
brew install libvterm
brew install libx11
brew install libxau
brew install libxcb
brew install libxcrypt
brew install libxdamage
brew install libxdmcp
brew install libxext
brew install libxfixes
brew install libxi
brew install libxinerama
brew install libxml2
brew install libxrandr
brew install libxrender
brew install libxshmfence
brew install libxt
brew install libxtst
brew install libxv
brew install libxvmc
brew install libxxf86vm
brew install linux-headers@5.15
brew install little-cms2
brew install lm-sensors
brew install lua
brew install luajit-openresty
brew install luarocks
brew install luv
brew install lz4
brew install lzo
brew install m4
brew install mmv
brew install mpdecimal
brew install mpfr
brew install msgpack
brew install navi
brew install ncurses
brew install nettle
brew install nghttp2
brew install node
brew install oniguruma
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssl@1.1
brew install openssl@3
brew install p11-kit
brew install patchelf
brew install pcre
brew install pcre2
brew install perl
brew install pixman
brew install pkg-config
brew install pygments
brew install python@3.11
brew install readline
brew install ripgrep
brew install rtmpdump
brew install rust
brew install sqlite
brew install starship
brew install terraformer
brew install texinfo
brew install tfenv
brew install tflint
brew install tfsec
brew install tree-sitter
brew install unbound
brew install unibilium
brew install unzip
brew install util-linux
brew install wayland
brew install wayland-protocols
brew install xinput
brew install xorgproto
brew install xz
brew install yuicompressor
brew install zip
brew install zlib
brew install zstd

brew cleanup

fi
