add_newline = false

[line_break]
disabled = true

[character]
symbol = "Î»"
#symbol = "â‹Š>"

[git_status]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

