add_newline = false

[status]
symbol = "✖"
format = '[$symbol $signal_name$maybe_int]($style) '
disabled = false

[gcloud]
disabled = true

[git_branch]
# truncation_length = 10
truncation_symbol = "…"

[git_status]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[aws]
disabled = true

[time]
disabled = false

