add_newline = false

[character]
# アイコンフォントを使うと、タブを押して補完する際にプロンプトがずれるので、それを避けるために">"を使う
success_symbol = '[>](bold green)'

# Disable the package module, hiding it from the prompt completely
[status]
symbol = "✖"
format = '[$symbol $signal_name$maybe_int]($style) '
disabled = false

[gcloud]
disabled = true

[git_branch]
# truncation_length = 10
truncation_symbol = "…"

[git_status]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[aws]
disabled = true

[time]
disabled = false

