add_newline = false

[git_branch]
truncation_length = 6
truncation_symbol = "…"

[git_status]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[aws]
disabled = true
