name: ci

on:
  pull_request:
    branches: ['*']
  push:
    branches:
      - main
      - master

jobs:
  install-deps:
    name: run-bootstrap
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v1
    - uses: actions/checkout@v3

    - name: run bootstrap script
      run: |
        # brew.shはbrew installを大量に実行しているだけなので、ciではbootstrap.shのみの検証とする
        ./bootstrap.sh
